spring:
  datasource:
    url: jdbc:mysql://localhost/TodoList?useUnicode=yes&characterEncoding=utf8&&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect